#!/usr/bin/lua

local juci = require("juci.core");
local network = require("juci.network");
local json = require("juci.json");

local function get_ipv4leases()
	local leases = network.ipv4leases();
	print(json.encode(leases));
end

juci.ubus({
	["ipv4leases"] = get_ipv4leases
}, arg);
