#!/usr/bin/lua

local juci = require("juci.core"); 
local json = require("juci.json"); 
require("ubus"); 

local conn = ubus.connect(); 
local acl = conn:call("session", "access", { ubus_rpc_session = juci.query("sid") }); 


if(not juci.session.access(juci.query("sid"), "juci-backup-iup", "download", { "read" })) then 
	print("Content-Type: text/plain\n"); 
	print("Access Denied!"); 
	os.exit(1); 
end 

local date = os.date("%Y-%m-%d"); 
io.write("Content-Type: application/x-targz\r\n");
io.write(string.format("Content-Disposition: attachment; filename=\"provisioning-Inteno-%s.tar.gz\"\r\n\r\n", date));

local output = juci.shell(string.format("sysupgrade --create-backup-uci -")); 
io.write(output); 

