#!/bin/bash

npm install
grunt 

for file in `find htdocs/js/ -name "*.js"`; do 
	echo "Compiling JS ${file}.."
	uglifyjs ${file} > ${file}.out
	mv ${file}.out ${file}
done

for file in `find htdocs/css/ -name "*.css"`; do 
	echo "Compiling CSS ${file}.."
	yui-compressor ${file} > ${file}.out
	mv ${file}.out ${file}
done
