#!/bin/bash

set -e 

WWW="$1"
MODE="$2"
MODE=${MODE:="RELEASE"}


if [ "$MODE" == "RELEASE" ]; then
	JS_WILDCARD="*.js.gz"
	CSS_WILDCARD="*.css.gz"
else
	JS_WILDCARD="*.js"
	CSS_WILDCARD="*.css"
fi

echo "Using mode: $MODE..."

if [ -n "$1" ]; then
	WWW="$1"
elif [ -d /www ]; then
	WWW="/www"
elif [ -d /var/www ]; then
	WWW="/var/www"
fi

#rm -f $WWW/__all.js
#for file in $WWW/js/*.js; do
#	cat $file >> $WWW/__all.js
#done

#rm -f $WWW/__all.css
#for file in $WWW/css/*.css; do
#	cat $file >> $WWW/__all.css
#done

if [ "$MODE" == "RELEASE" ]; then
	for file in `find ${WWW} -type f | grep -v "\.gz" | grep -v cgi-bin`; do
		echo "Compressing ${file}..."; 
		gzip -f ${file}
	done
fi

# now update the index file to include any extra files
INDEX=${WWW}/index.html
#gunzip -f ${INDEX}.gz
mkdir -p ${WWW}/js;
mkdir -p ${WWW}/css;

STYLES_HTML="" #"<link href='__all.css' rel='stylesheet' type='text/css' />"
SCRIPTS_HTML="" #"<script src='__all.js'></script>"
for file in `find ${WWW}/css -name "$CSS_WILDCARD" | sort`; do
	echo "Adding $file to index"
	style=${file#${WWW}}
	style=${style%.gz}
	STYLES_HTML="${STYLES_HTML}<link href='${style}' rel='stylesheet' type='text/css' />"
done

#sed "/<!-- STYLES_BEGIN -->/,/<!-- STYLES_END -->/c<!-- STYLES_BEGIN -->${STYLES_HTML}<!-- STYLES_END -->" ${INDEX} 
#cat ${INDEX} | tr -d '\n' | sed "s/<!-- STYLES_BEGIN -->.*<!-- STYLES_END -->/<!-- STYLES_BEGIN -->${STYLES_HTML}<!-- STYLES_END -->/" 
#cat /www/index.html | tr -d '\n' | sed "s/<!-- STYLES_BEGIN -->.*<!-- STYLES_END -->/<!-- STYLES_BEGIN -->test<!-- STYLES_END -->/g" 

for file in `find ${WWW}/js -name "$JS_WILDCARD" | sort`; do
	echo "Adding $file to index"
	JSFILE=${file#${WWW}}
	JSFILE=${JSFILE%.gz}
	SCRIPTS_HTML="${SCRIPTS_HTML}<script src=\"${JSFILE}\"></script>"
done
#cat ${INDEX} | tr -d '\n' | sed "s/<!-- SCRIPTS_BEGIN -->.*<!-- SCRIPTS_END -->/<!-- SCRIPTS_BEGIN -->${SCRIPTS_HTML}<!-- SCRIPTS_END -->/" 

# temporary fix for copying hardware config to config. Maybe we will move it there permanently later...
if [ -f /lib/db/config/hw ]; then
	cp /lib/db/config/hw /etc/config/hardware
fi 

# workaround because stupid f**ing sed is not working on busybox #@"#"!"¤¤"#!"¤!½!!!
echo "<!doctype html>
<html lang='en' >
<head>
	<meta charset='utf-8'>
	<meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'>
	<title >juci Express</title><!--ng-bind='title'-->
	<base href='/'>
	${STYLES_HTML}
</head>
<body role='document' ng-cloak >
	<div ui-view='content' style='min-height: 1000px;'></div>
	
	<div style='margin-bottom: 40px'></div>
	${SCRIPTS_HTML}
</body>
</html>" > ${INDEX}

if [ "$MODE" == "RELEASE" ]; then
	gzip -f ${INDEX}
fi
