#!/bin/sh

set -e 

WWW="$1"
MODE="$2"

if [ -n "$1" ]; then
	WWW="$1"
elif [ -d /www ]; then
	WWW="/www"
elif [ -d /var/www ]; then
	WWW="/var/www"
fi

rm -f $WWW/__all.js
for file in $WWW/js/*; do
	cat $file >> $WWW/__all.js
done

rm -f $WWW/__all.css
for file in $WWW/css/*; do
	cat $file >> $WWW/__all.css
done

if [ "$MODE" == "RELEASE" ]; then
	rm -rf ${WWW}/js
	rm -rf ${WWW}/css

	for file in `find ${WWW} -type f | grep -v "\.gz"`; do
		echo "Compressing ${file}..."; 
		gzip -f ${file}
	done
fi
