#!/bin/bash

# ensure that bash exits with non-zero status if any command fails!
set -e 

grunt --force

for file in `find bin/www/js/ -name "*.js"`; do 
	echo "Compiling JS ${file}.."
	uglifyjs ${file} > ${file}.out
	mv ${file}.out ${file}
done

for file in `find bin/www/css/ -name "*.css"`; do 
	echo "Compiling CSS ${file}.."
	yui-compressor ${file} > ${file}.out
	mv ${file}.out ${file}
done
