#!/bin/bash

ROUTER="$1"

set -e 

make clean && make DEFAULT_THEME=y
scp ~/.ssh/id_rsa.pub "root@$ROUTER:/etc/dropbear/authorized_keys"
scp -r htdocs/* root@$ROUTER:/www/
scp -r menu.d/* root@$ROUTER:/usr/share/rpcd/menu.d/
