#!/usr/bin/env lua 

require("ubus"); 

local conn = ubus.connect(); 
local INTERFACE = os.getenv("INTERFACE"); 
local ACTION = os.getenv("ACTION"); 

if(INTERFACE and (INTERFACE:find("usb") or INTERFACE:find("wwan"))) then 
	local result = conn:call("uci", "get", { config = "network" }); 
	if(result and result["values"] and result["values"]["defaults"]) then 
		local config = result["values"]; 
		local interface = config[config["defaults"]["internet_interface"]]; 
		if(ACTION == "add" or ACTION == "register") then 
			if (interface and not string.find(interface["ifname"], INTERFACE)) then 
				conn:call("uci", "set", { config = "network", section = interface[".name"], values = { ifname = interface["ifname"].." "..INTERFACE }}); 
				conn:call("uci", "commit", { config = "network" }); 
				conn:call("network", "reload", {}); 
				conn:send("juci", { event = "dongle-up", device = INTERFACE }); 
				os.execute("echo 'Added "..INTERFACE.." to network "..interface[".name"].."' > /dev/console"); 
			else 
				os.execute("echo 'Interface "..INTERFACE.." already added to network "..interface[".name"].."' > /dev/console"); 
			end 
		elseif(ACTION == "remove" or ACTION == "unregister") then 
			if (interface and string.find(interface["ifname"], INTERFACE)) then 
				conn:call("uci", "set", { config = "network", section = interface[".name"], values = { ifname = string.gsub(interface["ifname"], INTERFACE, "")}}); 
				conn:call("uci", "commit", { config = "network" });
				conn:call("network", "reload", {}); 
				conn:send("juci", { event = "dongle-down", device = INTERFACE }); 
				os.execute("echo 'Removed "..INTERFACE.." from network "..interface[".name"].."' > /dev/console"); 
			else 
				os.execute("echo 'Interface "..INTERFACE.." was not removed from network "..interface[".name"].."' > /dev/console"); 
			end 
		end
	end
end

conn:close(); 
