#!/usr/bin/lua

local juci = require("juci/core"); 

function list_modems()
	local data = juci.shell("ls /dev/tty*S*");
	local modems = {};
	for line in data:gmatch("[^\r\n]+") do
		table.insert(modems, line);
	end
	if next(myTable) == nil then
		data = juci.shell("ls /dev/tts/*");
		for line in data:gmatch("[\r\n]+") do
			table.insert(modems, line);
		end
	end
	print(json.encode({ modems = modems }));
end


juci.ubus({
	["list"] = list_modems
}, arg); 
