define Plugin/juci-macdb/install 
	$(INSTALL_DIR) $(1)/usr/share/macdb/
	$(INSTALL_DIR) $(1)/usr/bin/
	$(CP) $(PLUGIN_DIR)/src/macdb.txt $(1)/usr/share/macdb/db.txt
	$(CP) $(PLUGIN_DIR)/src/maclookup $(1)/usr/bin
endef 	
