gettext("phone.title");
gettext("Phone");
gettext("phone.call.log.title");
gettext("Call Log");
gettext("phone.number.blocking.title");
gettext("Number Blocking");
gettext("phone.ringing.schedule.title");
gettext("Ringing Schedule");
gettext("phone.numbers.title");
gettext("Phone Numbers");
gettext("phone.lines.title");
gettext("Phone Lines");
gettext("phone.speed.dialing.title");
gettext("Speed Dialing");
gettext("internet.ethernet.adsl.title");
gettext("ADSL");
gettext("internet.ethernet.vdsl.title");
gettext("VDSL");
gettext("status.status.dsl.title");
gettext("DSL");
gettext("internet.ethernet.phy.title");
gettext("Ethernet");
gettext("internet.ethernet.vlan.title");
gettext("VLAN");
gettext("wifi.title");
gettext("WiFi");
gettext("wifi.general.title");
gettext("General");
gettext("wifi.general.devices.title");
gettext("Radios");
gettext("wifi.general.interfaces.title");
gettext("Interfaces");
gettext("wifi.general.clients.title");
gettext("Clients");
gettext("wifi.schedule.title");
gettext("Schedule");
gettext("wifi.wps.title");
gettext("WPS");
gettext("wifi.mac.filter.title");
gettext("MAC filter");
gettext("wifi.client.title");
gettext("WiFi Client");
gettext("wifi.settings.title");
gettext("Settings");
gettext("internet.ethernet.wifi.title");
gettext("WiFi");
gettext("internet.wan.ddns.title");
gettext("DDNS");
gettext("internet.dns.title");
gettext("DNS & DDNS");
gettext("status.diagnostics.title");
gettext("Diagnostics");
gettext("internet.lan.dhcp.title");
gettext("DHCP Server");
gettext("internet.firewall.title");
gettext("Firewall");
gettext("internet.firewall.zones.title");
gettext("Zones");
gettext("internet.firewall.rules.title");
gettext("Rules");
gettext("internet.firewall.forwarding.title");
gettext("Forwarding");
gettext("internet.firewall.urlblock.title");
gettext("URL Filter");
gettext("internet.firewall.wordfilter.title");
gettext("Keyword Filter");
gettext("internet.firewall.svcfilter.title");
gettext("Service Filter");
gettext("internet.firewall.port.mapping.title");
gettext("Port Mapping");
gettext("internet.wan.exposed.host.title");
gettext("DMZ");
gettext("internet.parental.control.title");
gettext("Parental Control");
gettext("internet.lan.iptv.title");
gettext("IPTV");
gettext("status.status.tv.title");
gettext("IPTV");
gettext("internet.services.minidlna.title");
gettext("MiniDLNA");
gettext("status.title");
gettext("Status");
gettext("status.status.title");
gettext("Status");
gettext("status.status.system.title");
gettext("System");
gettext("status.status.services.title");
gettext("Services");
gettext("status.events.title");
gettext("Events");
gettext("status.restart.title");
gettext("Restart");
gettext("status.about.title");
gettext("About");
gettext("settings.password.title");
gettext("Router Password");
gettext("settings.system.title");
gettext("System");
gettext("settings.upgrade.title");
gettext("Firmware Upgrade");
gettext("settings.energy.title");
gettext("Energy Settings");
gettext("settings.configuration.title");
gettext("Configuration");
gettext("settings.network.title");
gettext("Network");
gettext("internet.title");
gettext("Internet");
gettext("internet.ethernet.title");
gettext("Devices");
gettext("internet.network.title");
gettext("Connections");
gettext("internet.wan.title");
gettext("WAN");
gettext("internet.lan.title");
gettext("LAN");
gettext("internet.services.title");
gettext("Services");
gettext("status.nat.title");
gettext("NAT");
gettext("internet.services.samba.title");
gettext("Samba");
gettext("status.usb.title");
gettext("USB");
gettext("overview.title");
gettext("Overview");
gettext("settings.title");
gettext("Settings");