#!/bin/bash

for file in $1; do
	# extract all angular filter translations
	grep -RPoin "{{[[:space:]]*'.*'[[:space:]]*\|[[:space:]]*translate[[:space:]]*}}" $file|awk "BEGIN{FS=\":\"}{ match(\$2, /'(.*)'/, arr); print \"# $file :\" \$1 \"\nmsgid \\\"\" arr[1] \"\\\"\nmsgstr \\\"\\\"\n\" }"
	# extract all html tag translations
	grep -RPoin "<([a-z\-_0-9]+?).*?translate.*?>(.*?)<\/\1>" $file | awk "BEGIN{FS=\":\"}{ match(\$2, /translate.*?>(.*)<.*/, arr); print \"# $file: \" \$1 \"\nmsgid \\\"\" arr[1] \"\\\"\nmsgstr \\\"\\\"\n\"; }"
	# extract all gettext(...) translations
	grep -RPoin "gettext\(\"(.*?)\"\)" $file | awk "BEGIN{FS=\":\"}{ match(\$2, /gettext\(\"(.*)\"\)/, arr); print \"# $file: \" \$1 \"\nmsgid \\\"\" arr[1] \"\\\"\nmsgstr \\\"\\\"\n\"; }"
done
