#!/bin/bash
# Copyright (c) 2016 Martin Schröder <mkschreder.uk@gmail.com>

for dir in `find plugins/ -mindepth 1 -maxdepth 1 -type d | sort`; do
	echo "LISTING $dir"
	grep -Roh "\$rpc\.[^\(\)]*" $dir | sort | uniq 
	grep -Roh "\$uci\.[^\.\[\(\)]*" $dir | sort | uniq
done
