#!/bin/sh 
local SUCCESS=0

local send=$1
local receive=$2
local sent="-"
local received="-"

if [ "$send" != "done" ]; then
	sent=$(tptest $send | awk '/Throughput/{print($2)}')
fi
if [ "$receive" != "done" ]; then
	received=$(tptest $receive | awk '/Throughput/{print($2)}')
fi
ubus send juci.utils.speedtest '{"status":'$SUCCESS', "upstream":'$sent',"downstream":'$received'}'

