gettext("overview.title");
gettext("Overview");
gettext("phone.title");
gettext("Phone");
gettext("phone.call.log.title");
gettext("Call Log");
gettext("phone.number.blocking.title");
gettext("Number Blocking");
gettext("phone.ringing.schedule.title");
gettext("Ringing Schedule");
gettext("phone.numbers.title");
gettext("SIP Accounts");
gettext("phone.lines.title");
gettext("Phone Lines");
gettext("phone.speed.dialing.title");
gettext("Speed Dialing");
gettext("phone.dect.title");
gettext("DECT");
gettext("internet.title");
gettext("Network");
gettext("internet.ethernet.title");
gettext("Devices");
gettext("internet.ethernet.phy.title");
gettext("Ethernet");
gettext("internet.ethernet.adsl.title");
gettext("ADSL");
gettext("internet.ethernet.vdsl.title");
gettext("VDSL");
gettext("internet.ethernet.wifi.title");
gettext("Wireless");
gettext("internet.ethernet.vlan.title");
gettext("VLAN");
gettext("internet.network.title");
gettext("Connections");
gettext("internet.routes.title");
gettext("Routes");
gettext("internet.firewall.title");
gettext("Firewall");
gettext("internet.firewall.zones.title");
gettext("Zones");
gettext("internet.firewall.rules.title");
gettext("Rules");
gettext("internet.firewall.forwarding.title");
gettext("Forwarding");
gettext("internet.firewall.urlblock.title");
gettext("URL Filter");
gettext("internet.firewall.wordfilter.title");
gettext("Keyword Filter");
gettext("internet.firewall.svcfilter.title");
gettext("Service Filter");
gettext("internet.firewall.port.mapping.title");
gettext("Port Mapping");
gettext("internet.firewall.dmz.title");
gettext("DMZ");
gettext("internet.parental.control.title");
gettext("Parental Control");
gettext("internet.multiwan.title");
gettext("MultiWAN");
gettext("internet.services.title");
gettext("Services");
gettext("internet.services.minidlna.title");
gettext("MiniDLNA");
gettext("internet.services.ntp.title");
gettext("NTP");
gettext("internet.services.upnp.title");
gettext("UPnP");
gettext("internet.services.ddns.title");
gettext("DDNS");
gettext("internet.services.samba.title");
gettext("Samba");
gettext("wifi.title");
gettext("WiFi");
gettext("wifi.general.title");
gettext("General");
gettext("wifi.general.devices.title");
gettext("Radios");
gettext("wifi.general.interfaces.title");
gettext("Interfaces");
gettext("wifi.general.clients.title");
gettext("Clients");
gettext("wifi.schedule.title");
gettext("Schedule");
gettext("wifi.wps.title");
gettext("WPS");
gettext("wifi.mac.filter.title");
gettext("MAC filter");
gettext("wifi.client.title");
gettext("WiFi Client");
gettext("settings.title");
gettext("System");
gettext("settings.system.title");
gettext("General");
gettext("settings.password.title");
gettext("Router Password");
gettext("settings.upgrade.title");
gettext("Firmware Upgrade");
gettext("settings.upgrade.options.title");
gettext("Options");
gettext("settings.configuration.title");
gettext("Backup");
gettext("settings.management.title");
gettext("Management");
gettext("settings.management.dropbear.title");
gettext("SSH");
gettext("settings.management.uhttpd.title");
gettext("HTTPD");
gettext("settings.management.services.title");
gettext("Services");
gettext("settings.services.title");
gettext("Services");
gettext("status.title");
gettext("Status");
gettext("status.system.title");
gettext("System");
gettext("status.system.processes.title");
gettext("Processes");
gettext("status.tv.title");
gettext("IPTV");
gettext("status.wifi.title");
gettext("Wireless");
gettext("status.dsl.title");
gettext("DSL");
gettext("status.usb.title");
gettext("USB");
gettext("status.network.title");
gettext("Network");
gettext("status.network.clients.title");
gettext("Clients");
gettext("status.network.routes.title");
gettext("Routes");
gettext("status.network.upnpd.title");
gettext("UPnP");
gettext("status.network.nat.title");
gettext("NAT");
gettext("status.diagnostics.title");
gettext("Diagnostics");
gettext("status.phone.title");
gettext("Phone");
gettext("status.events.title");
gettext("Events");
gettext("status.restart.title");
gettext("Restart");
gettext("status.about.title");
gettext("About");