#!/usr/bin/lua

local juci = require("juci/core"); 
local FILEPATH="/etc/dropbear/authorized_keys"
function dropbear_getpublickeys(opts)
	local res = {};
	local file = io.open(FILEPATH, "r");
	for line in file:lines() do
		local parts= {};
		local i =0
		for w in line:gmatch("%S+") do
		  	table.insert(parts,w);
		end
		table.insert ( res,{
			type = parts[1], 
			key = parts[2],
			id = parts[3] 
		});
	end
	file:close();
	print(json.encode({keys=res}));
end

function dropbear_addpublickey(opts)
       if(not opts["key"]) then return; end;
       --[ TODO: add check of ]--
	   juci.shell('echo "'.. opts["key"] .. "\" >> " .. FILEPATH);
end

function dropbear_removepublickey(opts)
	if(not opts["type"]) then print(json.encode({res="noType"})); return; end;
	if(not opts["key"])  then print(json.encode({res="noKey"})); return; end;
	if(not opts["id"])   then print(json.encode({res="noId"})); return; end;
	local keyToRemove=  opts["type"] .. " " .. opts["key"] .. " " .. opts["id"]
	local command= 'cat ' .. FILEPATH .. ' |grep -v "' .. keyToRemove .. '" > /tmp/auth';
	juci.shell(command);
	juci.shell('mv /tmp/auth '.. FILEPATH);
	print(json.encode({res="ok"}));
end



juci.ubus({
	["get_public_keys"] = dropbear_getpublickeys,
	["add_public_key"] = dropbear_addpublickey,
	["remove_public_key"] = dropbear_removepublickey

}, arg); 
